package clases;
// Generated 03-jul-2018 18:56:13 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;

/**
 * Detfac generated by hbm2java
 */
public class Detfac implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Factura factura;
	private Producto producto;
	private BigDecimal precio;
	private int cantidad;
	private BigDecimal total;
	private int dte;

	public Detfac() {
	}

	public Detfac(Factura factura, Producto producto, BigDecimal precio, int cantidad, BigDecimal total, int dte) {
		this.factura = factura;
		this.producto = producto;
		this.precio = precio;
		this.cantidad = cantidad;
		this.total = total;
		this.dte = dte;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	public int getDte() {
		return this.dte;
	}

	public void setDte(int dte) {
		this.dte = dte;
	}

}
