package clases;
// Generated 03-jul-2018 18:56:13 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Usuario usuario;
	private Date fecha;
	private Set<Detfac> detfacs = new HashSet<Detfac>(0);

	public Factura() {
	}

	public Factura(Usuario usuario, Date fecha) {
		this.usuario = usuario;
		this.fecha = fecha;
	}

	public Factura(Usuario usuario, Date fecha, Set<Detfac> detfacs) {
		this.usuario = usuario;
		this.fecha = fecha;
		this.detfacs = detfacs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Set<Detfac> getDetfacs() {
		return this.detfacs;
	}

	public void setDetfacs(Set<Detfac> detfacs) {
		this.detfacs = detfacs;
	}

}
