package clases;
// Generated 03-jul-2018 18:56:13 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Categoria categoria;
	private String nombre;
	private String marca;
	private BigDecimal precio;
	private String descripcion;
	private int stock;
	private String imagen;
	private Set<Detfac> detfacs = new HashSet<Detfac>(0);

	public Producto() {
	}

	public Producto(Categoria categoria, String nombre, String marca, BigDecimal precio, String descripcion, int stock,
			String imagen) {
		this.categoria = categoria;
		this.nombre = nombre;
		this.marca = marca;
		this.precio = precio;
		this.descripcion = descripcion;
		this.stock = stock;
		this.imagen = imagen;
	}

	public Producto(Categoria categoria, String nombre, String marca, BigDecimal precio, String descripcion, int stock,
			String imagen, Set<Detfac> detfacs) {
		this.categoria = categoria;
		this.nombre = nombre;
		this.marca = marca;
		this.precio = precio;
		this.descripcion = descripcion;
		this.stock = stock;
		this.imagen = imagen;
		this.detfacs = detfacs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public Set<Detfac> getDetfacs() {
		return this.detfacs;
	}

	public void setDetfacs(Set<Detfac> detfacs) {
		this.detfacs = detfacs;
	}

}
