package clases.pildoras;
// Generated 25-jun-2018 17:11:21 by Hibernate Tools 5.2.10.Final

/**
 * Archivo generated by hbm2java
 */
public class Archivo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4757307499248449886L;
	private Integer id;
	private String nombre;
	private String tipo;
	private byte[] contenido;

	public Archivo() {
	}

	public Archivo(String nombre, String tipo, byte[] contenido) {
		this.nombre = nombre;
		this.tipo = tipo;
		this.contenido = contenido;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public byte[] getContenido() {
		return this.contenido;
	}

	public void setContenido(byte[] contenido) {
		this.contenido = contenido;
	}

}
