package clases.pildoras;
// Generated 25-jun-2018 17:11:21 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4243976704498983275L;
	private String codcli;
	private String empresa;
	private String dir;
	private String pob;
	private String telf;
	private String responsable;
	private String historial;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Cliente() {
	}

	public Cliente(String codcli) {
		this.codcli = codcli;
	}

	public Cliente(String codcli, String empresa, String dir, String pob, String telf, String responsable,
			String historial, Set<Pedido> pedidos) {
		this.codcli = codcli;
		this.empresa = empresa;
		this.dir = dir;
		this.pob = pob;
		this.telf = telf;
		this.responsable = responsable;
		this.historial = historial;
		this.pedidos = pedidos;
	}

	public String getCodcli() {
		return this.codcli;
	}

	public void setCodcli(String codcli) {
		this.codcli = codcli;
	}

	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	public String getDir() {
		return this.dir;
	}

	public void setDir(String dir) {
		this.dir = dir;
	}

	public String getPob() {
		return this.pob;
	}

	public void setPob(String pob) {
		this.pob = pob;
	}

	public String getTelf() {
		return this.telf;
	}

	public void setTelf(String telf) {
		this.telf = telf;
	}

	public String getResponsable() {
		return this.responsable;
	}

	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}

	public String getHistorial() {
		return this.historial;
	}

	public void setHistorial(String historial) {
		this.historial = historial;
	}

	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
