package clases.pildoras;
// Generated 25-jun-2018 17:11:21 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;

/**
 * Pedido generated by hbm2java
 */
public class Pedido implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8411884714069959096L;
	private int npedido;
	private Cliente cliente;
	private String fechapedido;
	private String formapago;
	private BigDecimal dte;
	private String enviado;

	public Pedido() {
	}

	public Pedido(int npedido) {
		this.npedido = npedido;
	}

	public Pedido(int npedido, Cliente cliente, String fechapedido, String formapago, BigDecimal dte, String enviado) {
		this.npedido = npedido;
		this.cliente = cliente;
		this.fechapedido = fechapedido;
		this.formapago = formapago;
		this.dte = dte;
		this.enviado = enviado;
	}

	public int getNpedido() {
		return this.npedido;
	}

	public void setNpedido(int npedido) {
		this.npedido = npedido;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getFechapedido() {
		return this.fechapedido;
	}

	public void setFechapedido(String fechapedido) {
		this.fechapedido = fechapedido;
	}

	public String getFormapago() {
		return this.formapago;
	}

	public void setFormapago(String formapago) {
		this.formapago = formapago;
	}

	public BigDecimal getDte() {
		return this.dte;
	}

	public void setDte(BigDecimal dte) {
		this.dte = dte;
	}

	public String getEnviado() {
		return this.enviado;
	}

	public void setEnviado(String enviado) {
		this.enviado = enviado;
	}

}
