package clases.pildoras;
// Generated 25-jun-2018 17:11:21 by Hibernate Tools 5.2.10.Final

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8404474902139899712L;
	@Override
	public String toString() {
		return "Producto [codart=" + codart + ", section=" + section + ", nomart=" + nomart + ", precio=" + precio
				+ ", fecha=" + fecha + ", importado=" + importado + ", porig=" + porig + ", foto=" + foto + "]" + "\n";
	}

	private String codart;
	private String section;
	private String nomart;
	private Long precio;
	private String fecha;
	private String importado;
	private String porig;
	private String foto;

	public Producto() {	
	}

	public Producto(String codart) {
		this.codart = codart;
	}

	public Producto(String codart, String section, String nomart, Long precio, String fecha, String importado,
			String porig, String foto) {
		this.codart = codart;
		this.section = section;
		this.nomart = nomart;
		this.precio = precio;
		this.fecha = fecha;
		this.importado = importado;
		this.porig = porig;
		this.foto = foto;
	}

	public String getCodart() {
		return this.codart;
	}

	public void setCodart(String codart) {
		this.codart = codart;
	}

	public String getSection() {
		return this.section;
	}

	public void setSection(String section) {
		this.section = section;
	}

	public String getNomart() {
		return this.nomart;
	}

	public void setNomart(String nomart) {
		this.nomart = nomart;
	}

	public Long getPrecio() {
		return this.precio;
	}

	public void setPrecio(Long precio) {
		this.precio = precio;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public String getImportado() {
		return this.importado;
	}

	public void setImportado(String importado) {
		this.importado = importado;
	}

	public String getPorig() {
		return this.porig;
	}

	public void setPorig(String porig) {
		this.porig = porig;
	}

	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

}
